channels:
- anaconda
- conda-forge
dependencies:
- python=3.6.2
- pip:
  - pandas==1.1.5
  - azureml-defaults~=1.38.0
  - joblib==0.17.0
- scikit-learn==0.23.2
name: azureml_a60a280abc6164cb96a53af6436220ad
